# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" install:install-file "-Dfile=gradle-8.6.0.jar" "-Dversion=8.6.0" "-DgroupId=com.android.tools.build"  "-DartifactId=builder" "-Dversion=8.6.0" "-Dpackaging=jar"
#  install:install-file "-Dfile=gradle-8.6.0.jar" "-Dversion=8.6.0" "-DgroupId=com.android.tools.build"  "-DartifactId=builder" "-Dversion=8.6.0" "-Dpackaging=jar"

 
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=aapt2-proto-8.6.0.jar" "-DpomFile=aapt2-proto-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=aaptcompiler-8.6.0.jar" "-DpomFile=aaptcompiler-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=builder-test-api-8.6.0.jar" "-DpomFile=builder-test-api-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=ddmlib-31.6.0.jar" "-DpomFile=ddmlib-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=gradle-8.6.0.jar" "-DpomFile=gradle-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=repository-31.6.0.jar" "-DpomFile=repository-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=sdk-common-31.6.0.jar" "-DpomFile=sdk-common-31.6.0.pom"



# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=annotations-31.6.0.jar" "-DpomFile=annotations-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=gradle-8.6.0.jar" "-DpomFile=gradle-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=aapt2-proto-8.6.0.jar" "-DpomFile=aapt2-proto-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=aaptcompiler-8.6.0.jar" "-DpomFile=aaptcompiler-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=annotations-31.6.0.jar" "-DpomFile=annotations-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=builder-model-8.6.0.jar" "-DpomFile=builder-model-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=builder-test-api-8.6.0.jar" "-DpomFile=builder-test-api-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=ddmlib-31.6.0.jar" "-DpomFile=ddmlib-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=gradle-8.6.0.jar" "-DpomFile=gradle-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=gradle-api-8.6.0.jar" "-DpomFile=gradle-api-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=gradle-settings-api-8.6.0.jar" "-DpomFile=gradle-settings-api-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=lint-model-31.6.0.jar" "-DpomFile=lint-model-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=repository-31.6.0.jar" "-DpomFile=repository-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=sdk-common-31.6.0.jar" "-DpomFile=sdk-common-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=sdklib-31.6.0.jar" "-DpomFile=sdklib-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=lint-typedef-remover-8.6.0.jar" "-DpomFile=lint-typedef-remover-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=databinding-compiler-common-8.6.0.jar" "-DpomFile=databinding-compiler-common-8.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=databinding-common:8.6.0" "-DpomFile=databinding-common:8.6.0"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file   "-Dfile=bundletool-1.16.0.jar" "-DpomFile=bundletool-1.16.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=common-31.6.0.jar" "-DpomFile=common-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=jetifier-core-1.0.0-beta10.jar" "-DpomFile=jetifier-core-1.0.0-beta10.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file "-Dfile=dvlib-31.6.0.jar" "-DpomFile=dvlib-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-retention-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-retention-proto-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-logcat-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-logcat-proto-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-apk-installer-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-apk-installer-proto-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=crash-31.6.0.jar" "-DpomFile=crash-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=shared-31.6.0.jar" "-DpomFile=shared-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=layoutlib-api-31.6.0.jar" "-DpomFile=layoutlib-api-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-device-provider-ddmlib-proto-31.6.0.jar" "-DpomFile=android-device-provider-ddmlib-proto-31.6.0.pom"
# & "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-device-provider-gradle-proto-31.6.0.jar" "-DpomFile=android-device-provider-gradle-proto-31.6.0.pom"
& "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-additional-test-output-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-additional-test-output-proto-31.6.0.pom"
& "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-coverage-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-coverage-proto-31.6.0.pom"
& "C:\Program Files\apache-maven-3.9.9\bin\mvn.cmd" org.apache.maven.plugins:maven-install-plugin:3.1.4:install-file  "-Dfile=android-test-plugin-host-emulator-control-proto-31.6.0.jar" "-DpomFile=android-test-plugin-host-emulator-control-proto-31.6.0.pom"